export const users = [
  {
    id: 1,
    avatar: "",
    name: "John Doe",
    email: "john.doe@example.com",
    events: 15,
    payment: "Unpaid",
    status: "Block",
  },
  {
    id: 2,
    avatar: "",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    events: 10,
    payment: "Paid",
    status: "Unblock",
  },
  {
    id: 3,
    avatar: "",
    name: "Test",
    email: "john.doe@example.com",
    events: 15,
    payment: "Unpaid",
    status: "Block",
  },
  {
    id: 4,
    avatar: "",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    events: 10,
    payment: "Unpaid",
    status: "Block",
  },
];
