export const users = [
  {
    id: 1,
    avatar: "",
    name: "John Doe",
    email: "john.doe1@example.com",
    events: 15,
    payment: "Unpaid",
    status: "Block",
  },
  {
    id: 2,
    avatar: "",
    name: "Jane Smith",
    email: "jane.smith2@example.com",
    events: 10,
    payment: "Paid",
    status: "Unblock",
  },
  {
    id: 3,
    avatar: "",
    name: "Robert Brown",
    email: "robert.brown3@example.com",
    events: 12,
    payment: "Paid",
    status: "Block",
  },
  {
    id: 4,
    avatar: "",
    name: "Linda Johnson",
    email: "linda.johnson4@example.com",
    events: 14,
    payment: "Unpaid",
    status: "Unblock",
  },
  {
    id: 5,
    avatar: "",
    name: "Michael Wilson",
    email: "michael.wilson5@example.com",
    events: 9,
    payment: "Unpaid",
    status: "Block",
  },
  {
    id: 6,
    avatar: "",
    name: "Sarah Garcia",
    email: "sarah.garcia6@example.com",
    events: 13,
    payment: "Paid",
    status: "Block",
  },
  {
    id: 7,
    avatar: "",
    name: "David Lee",
    email: "david.lee7@example.com",
    events: 11,
    payment: "Paid",
    status: "Unblock",
  },
  {
    id: 8,
    avatar: "",
    name: "Emily Rodriguez",
    email: "emily.rodriguez8@example.com",
    events: 16,
    payment: "Unpaid",
    status: "Block",
  },
  {
    id: 9,
    avatar: "",
    name: "James Martinez",
    email: "james.martinez9@example.com",
    events: 8,
    payment: "Paid",
    status: "Unblock",
  },
  {
    id: 10,
    avatar: "",
    name: "Patricia Lopez",
    email: "patricia.lopez10@example.com",
    events: 10,
    payment: "Paid",
    status: "Block",
  },
  {
    id: 11,
    avatar: "",
    name: "Paul Williams",
    email: "paul.williams11@example.com",
    events: 12,
    payment: "Unpaid",
    status: "Unblock",
  },
  {
    id: 12,
    avatar: "",
    name: "Nancy Davis",
    email: "nancy.davis12@example.com",
    events: 7,
    payment: "Unpaid",
    status: "Block",
  },
  {
    id: 13,
    avatar: "",
    name: "Kevin White",
    email: "kevin.white13@example.com",
    events: 10,
    payment: "Paid",
    status: "Block",
  },
  {
    id: 14,
    avatar: "",
    name: "Karen Taylor",
    email: "karen.taylor14@example.com",
    events: 11,
    payment: "Paid",
    status: "Unblock",
  },
  {
    id: 15,
    avatar: "",
    name: "Brian Anderson",
    email: "brian.anderson15@example.com",
    events: 12,
    payment: "Unpaid",
    status: "Block",
  },
  {
    id: 16,
    avatar: "",
    name: "Susan Jones",
    email: "susan.jones16@example.com",
    events: 10,
    payment: "Paid",
    status: "Block",
  },
  {
    id: 17,
    avatar: "",
    name: "Richard Thomas",
    email: "richard.thomas17@example.com",
    events: 9,
    payment: "Unpaid",
    status: "Unblock",
  },
  {
    id: 18,
    avatar: "",
    name: "Jessica Hernandez",
    email: "jessica.hernandez18@example.com",
    events: 11,
    payment: "Unpaid",
    status: "Block",
  },
  {
    id: 19,
    avatar: "",
    name: "Chris Young",
    email: "chris.young19@example.com",
    events: 10,
    payment: "Paid",
    status: "Unblock",
  },
  {
    id: 20,
    avatar: "",
    name: "Michelle King",
    email: "michelle.king20@example.com",
    events: 12,
    payment: "Paid",
    status: "Block",
  },
];
